baseurl = "https://chimpanji.github.io/example-hugo-site/"

title = "B&B Da Salvatore Noto"
theme = "Solar"
paginate = 5
publishDir = "docs"
pygmentsStyle = "solarized-dark" # solarized-light, -dark or -dark256

[params]
  scheme = "dark" # light, dark or gray
  description = "A wizard is never late"

[menu]
  [[menu.main]]
    name = "Feed"
    url = "/index.xml"
  [[menu.main]]
    name = "Repository"
    url = "https://github.com/bake/solar-theme-hugo"
  [[menu.other]]
    name = "Hugo"
    url = "https://themes.gohugo.io/solar-theme-hugo/"
  [[menu.other]]
    name = "Demo"
    url = "https://themes.gohugo.io/theme/solar-theme-hugo/"
